### ISSUE TITLE
parametre s= disparait dans les url diaporama

### ISSUE THREAD

**Issue by nicopuj** [mathalea/mathaleaV3#28]
Bonjour, 
quand on lance un diaporama en mode beta, le ou les paramètres choisis pour les exercices n'apparaissent pas dans l'url.
En fait ça charge la bonne url mais instantanément une page avec l'url sans les s=. En faisant retour arrière avec le navigateur on tombe sur la bonne url.
Ça le fait aussi quand on change le nombre de vues, affiche l'aperçu des questions/réponses.

**Comment by remiangot** [comment]
C'est corrigé dans la branche beta et bientôt dans main.
